[/Script/Engine.CollisionProfile]
+Profiles=(Name="Projectile",CollisionEnabled=QueryOnly,ObjectTypeName="Projectile",CustomResponses=,HelpMessage="Preset for projectiles",bCanModify=True)
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel1,Name="Projectile",DefaultResponse=ECR_Block,bTraceType=False,bStaticObject=False)
+EditProfiles=(Name="Trigger",CustomResponses=((Channel=Projectile, Response=ECR_Ignore)))

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/LordService_Menu.LordService_Menu
LocalMapOptions=
TransitionMap=
bUseSplitscreen=True
TwoPlayerSplitscreenLayout=Horizontal
ThreePlayerSplitscreenLayout=FavorTop
GameInstanceClass=/Script/Engine.GameInstance
GameDefaultMap=/Game/Maps/LordService_Menu.LordService_Menu
ServerDefaultMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Game/FirstPersonBP/Blueprints/FirstPersonGameMode.FirstPersonGameMode_C
GlobalDefaultServerGameMode=None

[/Script/IOSRuntimeSettings.IOSRuntimeSettings]
MinimumiOSVersion=IOS_12

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_FirstPersonBP",NewGameName="/Script/FPTemplate")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_FirstPersonBP",NewGameName="/Script/FPTemplate")

[/Script/Engine.RendererSettings]
r.CustomDepth=3

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=DE70347D4349DABAAA9B599EA6A05379
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=



[/Script/Engine.OnlineEngineInterface]
bUseOnlineServicesV2=True

[/Script/SocketSubsystemEOS.NetDriverEOSBase]
bIsUsingP2PSockets=True

[OnlineServices.EOS]
ProductId=46955ba99e6843dc944c2b1181148380
SandboxId=b8a0db9d7584497fb602f1792d610b4e
DeploymentId=0c2d699e06aa45bc9c061b0c27fed0d7
ClientId=xyza7891BmEGJWpAkprVmxNvVWQ40wID
ClientSecret=gTfGY9KfMk4NombCVvXryfS/tG5XzYrcBfbFX/DwEJs
ClientEncryptionKey=357538782F4125442A472D4B6150645367566B59703373367639792442264528
bDisableOverlay=false
bDisableSocialOverlay=false

[OnlineServices.Lobbies]
+SchemaDescriptors=(Id="GameLobby", ParentId="LobbyBase")

!SchemaCategoryAttributeDescriptors=ClearArray

+SchemaCategoryAttributeDescriptors=(SchemaId="LobbyBase", CategoryId="Lobby", AttributeIds=("SchemaCompatibilityId"))
;+SchemaAttributeDescriptors=(Id="GameMode", Type="String", Flags=("Public", "Searchable"), MaxSize=64)

+SchemaCategoryAttributeDescriptors=(SchemaId="GameLobby", CategoryId="LobbyMember", AttributeIds=("Appearance", "MemberAvatar", "MemberName"))
+SchemaAttributeDescriptors=(Id="Appearance", Type="String", Flags=("Public"), MaxSize=64)
+SchemaAttributeDescriptors=(Id="MemberAvatar", Type="String", Flags=("Public"), MaxSize=64)
+SchemaAttributeDescriptors=(Id="MemberName", Type="String", Flags=("Public"), MaxSize=64)

+SchemaCategoryAttributeDescriptors=(SchemaId="GameLobby", CategoryId="Lobby", AttributeIds=("GameSessionId", "LobbyName"))
+SchemaAttributeDescriptors=(Id="GameSessionId", Type="Int64", Flags=("Private"), MaxSize=64)
+SchemaAttributeDescriptors=(Id="LobbyName", Type="String", Flags=("Public"), MaxSize=64)

[OnlineServices.Stats]
!StatDefinitions=ClearDefinitions
+StatDefinitions=(Name=LoggedInCount, Id=0, ModifyMethod=Max)
+StatDefinitions=(Name=RandomNumber, Id=1, ModifyMethod=Set)
+StatDefinitions=(Name=Stat_Latest, Id=2, ModifyMethod=Largest, DefaultValue="Int64:0")
+StatDefinitions=(Name=Stat_Max, Id=3, ModifyMethod=Set, DefaultValue="Int64:0")
+StatDefinitions=(Name=Stat_Min, Id=4, ModifyMethod=Smallest, DefaultValue="Int64:999")
+StatDefinitions=(Name=Stat_Sum, Id=5, ModifyMethod=Sum, DefaultValue="Int64:0")
;+StatDefinitions=(Name=Stat_Type_Bool, Id=6, ModifyMethod=Set, DefaultValue="Bool:True")


[OnlineServices.Leaderboards]
bIsTitleManaged=true
!LeaderboardDefinitions=ClearDefinitions
+LeaderboardDefinitions=(Name=LB_LoggedInCount, Id=0, UpdateMethod=KeepBest, OrderMethod=Descending)



[URL]
GameName=LordService_Example

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
PackageName=com.ClusterfactGames.LordService

[/Script/Engine.UserInterfaceSettings]
RenderFocusRule=Never

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11

[OnlineServices]
DefaultServices=Epic

[OnlineServices.OSSAdapter]
!Services=ClearArray
+Services=(Service=Epic, OnlineSubsystem=EOS)
;+Services=(Service=Steam, OnlineSubsystem=Steam)

;// STEAM
;
;[OnlineSubsystemSteam]
;bEnabled=true
;SteamDevAppId=1284000
;SteamAppId=1284000
;GameServerQueryPort=27015
;bRelaunchInSteam=false
;GameVersion=1.0.0.0
;bVACEnabled=1
;bAllowP2PPacketRelay=true
;P2PConnectionTimeout=90
;; This is to prevent subsystem from reading other achievements that may be defined in parent .ini
;Achievement_0_Id=""
;
;[/Script/OnlineSubsystemSteam.SteamNetDriver]
;NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"
;
;
;[/Script/Engine.Engine]
;!NetDriverDefinitions=ClearArray
;+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemSteam.SteamNetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")
;
;
;// END OF STEAM

// EOS
[/Script/Engine.Engine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="SocketSubsystemEOS.NetDriverEOSBase",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver",MaxChannelsOverride=-1)
+NetDriverDefinitions=(DefName=" DemoNetDriver",DriverClassName="/Script/Engine.DemoNetDriver",DriverClassNameFallback="/Script/Engine.DemoNetDriver",MaxChannelsOverride=-1)

[/Script/Engine.Engine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="SocketSubsystemEOS.NetDriverEOSBase",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="DemoNetDriver",DriverClassName="/Script/Engine.DemoNetDriver",DriverClassNameFallback="/Script/Engine.DemoNetDriver")

[OnlineSubsystemEOS]
bEnabled=true

[/Script/OnlineSubsystemEOS.NetDriverEOS]
bIsUsingP2PSockets=true

[/Script/OnlineSubsystemEOS.EOSSettings]
CacheDir=CacheDir
DefaultArtifactName=UnrealClient
TickBudgetInMilliseconds=0
bEnableOverlay=False
bEnableSocialOverlay=False
bEnableEditorOverlay=False
bShouldEnforceBeingLaunchedByEGS=False
TitleStorageReadChunkLength=0
+Artifacts=(ArtifactName="UnrealClient",ClientId="xyza7891BmEGJWpAkprVmxNvVWQ40wID",ClientSecret="gTfGY9KfMk4NombCVvXryfS/tG5XzYrcBfbFX/DwEJs",ProductId="46955ba99e6843dc944c2b1181148380",SandboxId="b8a0db9d7584497fb602f1792d610b4e",DeploymentId="0c2d699e06aa45bc9c061b0c27fed0d7",ClientEncryptionKey="357538782F4125442A472D4B6150645367566B59703373367639792442264528")
-AuthScopeFlags=BasicProfile
-AuthScopeFlags=FriendsList
-AuthScopeFlags=Presence
+AuthScopeFlags=BasicProfile
+AuthScopeFlags=FriendsList
+AuthScopeFlags=Presence
bUseEAS=False
bUseEOSConnect=False
bMirrorStatsToEOS=False
bMirrorAchievementsToEOS=False
bUseEOSSessions=False
bMirrorPresenceToEAS=False

[OnlineSubsystem]
DefaultPlatformService=EOS

// END OF EOS

[Core.Log]
LogOnline=All
LogOnlineGame=All



